// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "MessageTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "MessageTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Demo::PosicionTypeSupport.

Demo::PosicionTypeSupport_ptr
TAO::Objref_Traits<Demo::PosicionTypeSupport>::duplicate (
    Demo::PosicionTypeSupport_ptr p)
{
  return Demo::PosicionTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Demo::PosicionTypeSupport>::release (
    Demo::PosicionTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Demo::PosicionTypeSupport_ptr
TAO::Objref_Traits<Demo::PosicionTypeSupport>::nil (void)
{
  return Demo::PosicionTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Demo::PosicionTypeSupport>::marshal (
    const Demo::PosicionTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Demo::PosicionTypeSupport::PosicionTypeSupport (void)
{}

Demo::PosicionTypeSupport::~PosicionTypeSupport (void)
{
}

Demo::PosicionTypeSupport_ptr
Demo::PosicionTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return PosicionTypeSupport::_duplicate (
      dynamic_cast<PosicionTypeSupport_ptr> (_tao_objref));
}

Demo::PosicionTypeSupport_ptr
Demo::PosicionTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return PosicionTypeSupport::_duplicate (
      dynamic_cast<PosicionTypeSupport_ptr> (_tao_objref));
}

Demo::PosicionTypeSupport_ptr
Demo::PosicionTypeSupport::_nil (void)
{
  return 0;
}

Demo::PosicionTypeSupport_ptr
Demo::PosicionTypeSupport::_duplicate (PosicionTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Demo::PosicionTypeSupport::_tao_release (PosicionTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Demo::PosicionTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Demo/PosicionTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Demo::PosicionTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Demo/PosicionTypeSupport:1.0";
}

::CORBA::Boolean
Demo::PosicionTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Demo::PosicionDataWriter.

Demo::PosicionDataWriter_ptr
TAO::Objref_Traits<Demo::PosicionDataWriter>::duplicate (
    Demo::PosicionDataWriter_ptr p)
{
  return Demo::PosicionDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Demo::PosicionDataWriter>::release (
    Demo::PosicionDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Demo::PosicionDataWriter_ptr
TAO::Objref_Traits<Demo::PosicionDataWriter>::nil (void)
{
  return Demo::PosicionDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Demo::PosicionDataWriter>::marshal (
    const Demo::PosicionDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Demo::PosicionDataWriter::PosicionDataWriter (void)
{}

Demo::PosicionDataWriter::~PosicionDataWriter (void)
{
}

Demo::PosicionDataWriter_ptr
Demo::PosicionDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return PosicionDataWriter::_duplicate (
      dynamic_cast<PosicionDataWriter_ptr> (_tao_objref));
}

Demo::PosicionDataWriter_ptr
Demo::PosicionDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return PosicionDataWriter::_duplicate (
      dynamic_cast<PosicionDataWriter_ptr> (_tao_objref));
}

Demo::PosicionDataWriter_ptr
Demo::PosicionDataWriter::_nil (void)
{
  return 0;
}

Demo::PosicionDataWriter_ptr
Demo::PosicionDataWriter::_duplicate (PosicionDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Demo::PosicionDataWriter::_tao_release (PosicionDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Demo::PosicionDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Demo/PosicionDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Demo::PosicionDataWriter::_interface_repository_id (void) const
{
  return "IDL:Demo/PosicionDataWriter:1.0";
}

::CORBA::Boolean
Demo::PosicionDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for Demo::PosicionDataReader.

Demo::PosicionDataReader_ptr
TAO::Objref_Traits<Demo::PosicionDataReader>::duplicate (
    Demo::PosicionDataReader_ptr p)
{
  return Demo::PosicionDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Demo::PosicionDataReader>::release (
    Demo::PosicionDataReader_ptr p)
{
  ::CORBA::release (p);
}

Demo::PosicionDataReader_ptr
TAO::Objref_Traits<Demo::PosicionDataReader>::nil (void)
{
  return Demo::PosicionDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Demo::PosicionDataReader>::marshal (
    const Demo::PosicionDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



Demo::PosicionDataReader::PosicionDataReader (void)
{}

Demo::PosicionDataReader::~PosicionDataReader (void)
{
}

Demo::PosicionDataReader_ptr
Demo::PosicionDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return PosicionDataReader::_duplicate (
      dynamic_cast<PosicionDataReader_ptr> (_tao_objref));
}

Demo::PosicionDataReader_ptr
Demo::PosicionDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return PosicionDataReader::_duplicate (
      dynamic_cast<PosicionDataReader_ptr> (_tao_objref));
}

Demo::PosicionDataReader_ptr
Demo::PosicionDataReader::_nil (void)
{
  return 0;
}

Demo::PosicionDataReader_ptr
Demo::PosicionDataReader::_duplicate (PosicionDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Demo::PosicionDataReader::_tao_release (PosicionDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Demo::PosicionDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Demo/PosicionDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Demo::PosicionDataReader::_interface_repository_id (void) const
{
  return "IDL:Demo/PosicionDataReader:1.0";
}

::CORBA::Boolean
Demo::PosicionDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

