/* -*- C++ -*- */
/* Generated by /home/ramiro/OpenDDS/bin/opendds_idl version 3.34.0-dev (ACE version 6.5.23) running on input file Message.idl */
#ifndef OPENDDS_IDL_GENERATED_MESSAGETYPESUPPORTIMPL_H_A7BQUZ
#define OPENDDS_IDL_GENERATED_MESSAGETYPESUPPORTIMPL_H_A7BQUZ

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 34, 0)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "MessageC.h"
#include "MessageTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/TypeSupportImpl_T.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Demo */



/* Begin STRUCT: Posicion */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct Demo_Posicion_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Demo_Posicion_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<Demo_Posicion_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Demo::Posicion& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::Demo::Posicion>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Demo::Posicion& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::Demo::Posicion>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::Demo::Posicion& stru);

void serialized_size(const Encoding& encoding, size_t& size, const ::Demo::Posicion& stru);

bool operator<<(Serializer& strm, const ::Demo::Posicion& stru);

bool operator>>(Serializer& strm,  ::Demo::Posicion& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::Demo::Posicion>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::Demo::Posicion>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly< ::Demo::Posicion>& stru);

template <>
struct MarshalTraits< ::Demo::Posicion> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound();
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(4);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::Demo::Posicion&) { return false; }
  static bool from_message_block( ::Demo::Posicion&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const  ::Demo::Posicion> stru);

bool operator<<(Serializer& strm, KeyOnly<const  ::Demo::Posicion> stru);

bool operator>>(Serializer& strm, KeyOnly< ::Demo::Posicion> stru);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Demo {
/// This structure supports use of std::map with one or more keys.
struct  Posicion_OpenDDS_KeyLessThan {
  bool operator()(const  ::Demo::Posicion& v1, const  ::Demo::Posicion& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.id < v2.id) return true;
    if (v2.id < v1.id) return false;
    return false;
  }
};
}

namespace Demo {
class PosicionTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::Demo::Posicion> {
  typedef  ::Demo::Posicion MessageType;
  typedef  ::Demo::PosicionSeq MessageSequenceType;
  typedef  ::Demo::PosicionSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::Demo::PosicionTypeSupport TypeSupportType;
  typedef  ::Demo::PosicionTypeSupportImpl TypeSupportImplType;
  typedef  ::Demo::PosicionDataWriter DataWriterType;
  typedef  ::Demo::PosicionDataReader DataReaderType;
  typedef  ::Demo::Posicion_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::Demo::Posicion> KeyOnlyType;
  typedef OpenDDS::DCPS::Demo_Posicion_xtag XtagType;

  static const char* type_name() { return "Demo::Posicion"; }
  static size_t key_count() { return 1; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace Demo {
class  PosicionTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<Posicion>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<Posicion>
{
public:
  typedef PosicionTypeSupport TypeSupportType;
  typedef PosicionTypeSupport::_var_type _var_type;
  typedef PosicionTypeSupport::_ptr_type _ptr_type;

  PosicionTypeSupportImpl() {}
  virtual ~PosicionTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  Posicion* create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const Posicion& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const Posicion& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, Posicion_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, Posicion_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static PosicionTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct< ::Demo::Posicion>();
bool gen_skip_over(Serializer& ser,  ::Demo::Posicion*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Demo::Posicion,  ::Demo::Posicion>(DDS::DynamicType_ptr type, const  ::Demo::Posicion& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Demo::Posicion,  ::Demo::Posicion>(DDS::DynamicType_ptr type,  ::Demo::Posicion& value);

template <>
const  ::Demo::Posicion* get_dynamic_data_adapter_value< ::Demo::Posicion,  ::Demo::Posicion>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Posicion */

/* End MODULE: Demo */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_MESSAGETYPESUPPORTIMPL_H_A7BQUZ */
