// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_MESSAGETYPESUPPORTC_PPR0PP_H_
#define _TAO_IDL_MESSAGETYPESUPPORTC_PPR0PP_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "MessageC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"
#include "dds/DdsDynamicDataC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 23
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace Demo
{

  
  // TAO_IDL - Generated from
  // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< Demo::Posicion, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> PosicionSeq;
  
  // TAO_IDL - Generated from
  // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_DEMO_POSICIONTYPESUPPORT__VAR_OUT_CH_)
#define _DEMO_POSICIONTYPESUPPORT__VAR_OUT_CH_

  class PosicionTypeSupport;
  typedef PosicionTypeSupport *PosicionTypeSupport_ptr;
  typedef TAO_Objref_Var_T<PosicionTypeSupport> PosicionTypeSupport_var;
  typedef TAO_Objref_Out_T<PosicionTypeSupport> PosicionTypeSupport_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  PosicionTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

    typedef PosicionTypeSupport_ptr _ptr_type;
    typedef PosicionTypeSupport_var _var_type;
    typedef PosicionTypeSupport_out _out_type;

    // The static operations.
    static PosicionTypeSupport_ptr _duplicate (PosicionTypeSupport_ptr obj);

    static void _tao_release (PosicionTypeSupport_ptr obj);

    static PosicionTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static PosicionTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static PosicionTypeSupport_ptr _nil (void);

    virtual ::DDS::ReturnCode_t create_sample_rc (
      ::Demo::Posicion & dst,
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::Demo::Posicion * create_sample (
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDS::ReturnCode_t create_dynamic_sample_rc (
      ::DDS::DynamicData_ptr & dst,
      const ::Demo::Posicion & src) = 0;

    virtual ::DDS::DynamicData_ptr create_dynamic_sample (
      const ::Demo::Posicion & src) = 0;

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::Demo::Posicion & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::Demo::Posicion & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::Demo::Posicion_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::Demo::Posicion_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    PosicionTypeSupport (void);

    

    virtual ~PosicionTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (PosicionTypeSupport (const PosicionTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (PosicionTypeSupport (PosicionTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (PosicionTypeSupport &operator= (const PosicionTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (PosicionTypeSupport &operator= (PosicionTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };
  // TAO_IDL - Generated from
  // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_DEMO_POSICIONDATAWRITER__VAR_OUT_CH_)
#define _DEMO_POSICIONDATAWRITER__VAR_OUT_CH_

  class PosicionDataWriter;
  typedef PosicionDataWriter *PosicionDataWriter_ptr;
  typedef TAO_Objref_Var_T<PosicionDataWriter> PosicionDataWriter_var;
  typedef TAO_Objref_Out_T<PosicionDataWriter> PosicionDataWriter_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  PosicionDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

    typedef PosicionDataWriter_ptr _ptr_type;
    typedef PosicionDataWriter_var _var_type;
    typedef PosicionDataWriter_out _out_type;

    // The static operations.
    static PosicionDataWriter_ptr _duplicate (PosicionDataWriter_ptr obj);

    static void _tao_release (PosicionDataWriter_ptr obj);

    static PosicionDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static PosicionDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static PosicionDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::Demo::Posicion & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::Demo::Posicion & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::Demo::Posicion & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::Demo::Posicion & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::Demo::Posicion & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::Demo::Posicion & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::Demo::Posicion & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::Demo::Posicion & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Demo::Posicion & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Demo::Posicion & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    PosicionDataWriter (void);

    

    virtual ~PosicionDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (PosicionDataWriter (const PosicionDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (PosicionDataWriter (PosicionDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (PosicionDataWriter &operator= (const PosicionDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (PosicionDataWriter &operator= (PosicionDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };
  // TAO_IDL - Generated from
  // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_DEMO_POSICIONDATAREADER__VAR_OUT_CH_)
#define _DEMO_POSICIONDATAREADER__VAR_OUT_CH_

  class PosicionDataReader;
  typedef PosicionDataReader *PosicionDataReader_ptr;
  typedef TAO_Objref_Var_T<PosicionDataReader> PosicionDataReader_var;
  typedef TAO_Objref_Out_T<PosicionDataReader> PosicionDataReader_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  PosicionDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

    typedef PosicionDataReader_ptr _ptr_type;
    typedef PosicionDataReader_var _var_type;
    typedef PosicionDataReader_out _out_type;

    // The static operations.
    static PosicionDataReader_ptr _duplicate (PosicionDataReader_ptr obj);

    static void _tao_release (PosicionDataReader_ptr obj);

    static PosicionDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static PosicionDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static PosicionDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::Demo::PosicionSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::Demo::PosicionSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::Demo::Posicion & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::Demo::Posicion & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::Demo::PosicionSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::Demo::PosicionSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::Demo::PosicionSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::Demo::Posicion & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::Demo::Posicion & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    PosicionDataReader (void);

    

    virtual ~PosicionDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (PosicionDataReader (const PosicionDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (PosicionDataReader (PosicionDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (PosicionDataReader &operator= (const PosicionDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (PosicionDataReader &operator= (PosicionDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };


// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module Demo
// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DEMO_POSICIONTYPESUPPORT__TRAITS_)
#define _DEMO_POSICIONTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::Demo::PosicionTypeSupport>
  {
    static ::Demo::PosicionTypeSupport_ptr duplicate (
        ::Demo::PosicionTypeSupport_ptr p);
    static void release (
        ::Demo::PosicionTypeSupport_ptr p);
    static ::Demo::PosicionTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Demo::PosicionTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEMO_POSICIONDATAWRITER__TRAITS_)
#define _DEMO_POSICIONDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::Demo::PosicionDataWriter>
  {
    static ::Demo::PosicionDataWriter_ptr duplicate (
        ::Demo::PosicionDataWriter_ptr p);
    static void release (
        ::Demo::PosicionDataWriter_ptr p);
    static ::Demo::PosicionDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Demo::PosicionDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEMO_POSICIONDATAREADER__TRAITS_)
#define _DEMO_POSICIONDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::Demo::PosicionDataReader>
  {
    static ::Demo::PosicionDataReader_ptr duplicate (
        ::Demo::PosicionDataReader_ptr p);
    static void release (
        ::Demo::PosicionDataReader_ptr p);
    static ::Demo::PosicionDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Demo::PosicionDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1649

#if defined (__ACE_INLINE__)
#include "MessageTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

