// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "MessageC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "MessageC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /home/ramiro/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_structure/cdr_op_cs.cpp:48


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Demo::Posicion &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.id) &&
    (strm << _tao_aggregate.texto.in ()) &&
    (strm << _tao_aggregate.contador);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Demo::Posicion &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.id) &&
    (strm >> _tao_aggregate.texto.out ()) &&
    (strm >> _tao_aggregate.contador);
}

TAO_END_VERSIONED_NAMESPACE_DECL



